#!/bin/bash
#SBATCH -p matlab
#SBATCH --ntasks-per-node=24
#SBATCH --mail-user=nzz2102@stanford.edu
#SBATCH --mail-type=ALL
#SBATCH -t 2:00:00
#SBATCH -J FD3DSimPointSource
#SBATCH -o job-%j.out
#SBATCH -e job-%j.err

matlab -nodisplay -nosplash -r 'maxNumCompThreads(8)' << EOF

clear all; close all; clear classes; clc;
addpath /home/nzz2102/FDFD_3D/Basic3DVisualization;
MetaAtom3DTestVisualization;
exit;
EOF

